version: "3"

services:
#  module-svc:
#    build: .
#
#    expose:
#      - "8080"
#
#    ports:
#      - "8080:8080"
#
#    depends_on:
#      - moduledb
#
#    environment:
#      DATABASE_HOST: depsetdb
#      DATABASE_NAME: depsets
#      DATABASE_USER: depset_robot
#      DATABASE_PASSWORD: "d3p53t5"
#
  moduledb:
    image: postgres:11

    volumes:
      # Volume for startup scripts. Note this willonly run if there is nothing in /var/lib/postgresql/data
      - ./test/db/init-scripts:/docker-entrypoint-initdb.d

      # Volume for persistance between runs. Uncomment if you wish to retain data.
      # - ./test/db/volume:/var/lib/postgresql/data

    expose:
      - "5432"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: pgsqlDev01
